apiVersion: v1
kind : Service
metadata: 
  name: product-src
  labels:
    app: product

spec : 
  selector: 
    app: product-src
  ports: 
   - name: http
     port : 80
     targetPort: 3000
  type: ClusterIP
