apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: otel-servicemonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
    release: monitoring

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-opentelemetry
      app.kubernetes.io/name: opentelemetry-collector

  namespaceSelector:
    matchNames:
      - monitoring

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s